### ISSUE TITLE
Ошибка после загрузки на сервер

### ISSUE THREAD

**Issue by joganol** [realdigger/SMF-URL-Popup#1]
Привет, скачал всё в zip файл, при установке из админ панели появляется такая ошибка после загрузки:
Загрузка пакета прошла с ошибками:
"Несмотря на то, что пакет был загружен на сервер, он выглядит пустым и так далее куча текста.

Что делать?

**Comment by realdigger** [comment]
Для установки файлы в архиве должны быть без верхнего каталога.

**Comment by joganol** [comment]
Спасибо, я понял, перепаковал в zip и всё установилось.
